namespace LibrarySystem.Domain
{
	/// <summary>
	/// Represents a book in the library system.
	/// </summary>
	public class Book
	{
		/// <summary>
		/// Unique identifier of the book.
		/// </summary>
		public int BookId { get; private set; }

		/// <summary>
		/// Unique ISBN identifier of the book.
		/// </summary>
		public string Isbn { get; } = null!;

		/// <summary>
		/// Title of the book.
		/// </summary>
		public string Title { get; } = null!;

		/// <summary>
		/// Author of the book.
		/// </summary>
		public string Author { get; } = null!;

		/// <summary>
		/// Publication year of the book.
		/// </summary>
		public int PublicationYear { get; }

		/// <summary>
		/// List of copies of the book. 
		/// </summary>
		private readonly List<Copy> _copies = new();

		/// <summary>
		/// Private parameterless constructor for ORM use only.
		/// </summary>
		private Book() { }

		/// <summary>
		/// Constructor for a Book.
		/// </summary>
		/// <param name="isbn">ISBN identifier.</param>
		/// <param name="title">Book title.</param>
		/// <param name="author">Book author.</param>
		/// <param name="publicationYear">Year of publication.</param>
		/// <exception cref="ArgumentException">
		/// Thrown when <paramref name="isbn"/>, <paramref name="title"/> or <paramref name="author"/> 
		/// is empty, <paramref name="isbn"/> is invalid, or <paramref name="publicationYear"/> is in the future.
		/// </exception>
		public Book(string isbn, string title, string author, int publicationYear)
		{
			if (string.IsNullOrWhiteSpace(isbn))
				throw new ArgumentException("ISBN cannot be empty.", nameof(isbn));

			if (!IsValidIsbn(isbn))
				throw new ArgumentException("Isbn must be valid.", nameof(isbn));

			if (string.IsNullOrWhiteSpace(title))
				throw new ArgumentException("Title cannot be empty.", nameof(title));

			if (string.IsNullOrWhiteSpace(author))
				throw new ArgumentException("Author cannot be empty.", nameof(author));

			if (publicationYear > DateTime.Now.Year)
				throw new ArgumentException("Publication year cannot be in the future.", nameof(publicationYear));

			Isbn = isbn;
			Title = title;
			Author = author;
			PublicationYear = publicationYear;
		}

		/// <summary>
		/// Sets the unique identifier of the book after it has been generated by the database.
		/// </summary>
		/// <param name="id">The ID value returned by the database upon insertion.</param>
		/// <exception cref="ArgumentException">
		/// Thrown when <paramref name="id"/> is zero or negative.
		/// </exception>
		/// <exception cref="InvalidOperationException">
		/// Thrown when the book ID has already been set.
		/// </exception>
		internal void SetId(int id)
		{
			if (id <= 0)
				throw new ArgumentException("ID must be positive.", nameof(id));

			if (BookId != 0)
				throw new InvalidOperationException("ID has already been set.");

			BookId = id;
		}

		/// <summary>
		/// Checks whether a ISBN is valid.
		/// </summary>
		/// <param name="isbn">The ISBN identifier.</param>
		/// <returns>True if the ISBN is valid; otherwise, false.</returns>
		private static bool IsValidIsbn(string isbn)
		{
			var digits = isbn.Replace("-", "").Replace(" ", "");
			return digits.Length == 10 || digits.Length == 13;
		}

		/// <summary>
		/// Returns a read only collection of the book copies.
		/// </summary>
		/// <returns>The read only collection of copies.</returns>
		public IReadOnlyCollection<Copy> Copies()
		{
			return _copies.AsReadOnly();
		}

		/// <summary>
		/// Adds a copy to the collection of book copies.
		/// </summary>
		/// <param name="copy">The copy to add.</param>
		/// <exception cref="ArgumentNullException">Thrown when <paramref name="copy"/> is null.</exception>
		/// <exception cref="ArgumentException">Thrown when <paramref name="copy"/> does not belong to this book.</exception>
		public void AddCopy(Copy copy)
		{
			if (copy == null)
				throw new ArgumentNullException(nameof(copy));
			if (copy.Book != this)
				throw new ArgumentException("Copy must belong to this book.", nameof(copy));
			_copies.Add(copy);
		}

		/// <summary>
		/// Removes a copy from the collection of book copies.
		/// </summary>
		/// <param name="copy">The copy to remove.</param>
		/// <exception cref="ArgumentNullException">Thrown when <paramref name="copy"/> is null.</exception>
		/// <exception cref="ArgumentException">Thrown when <paramref name="copy"/> does not belong to this book.</exception>
		public void RemoveCopy(Copy copy)
		{
			if (copy == null)
				throw new ArgumentNullException(nameof(copy));
			if (copy.Book != this)
				throw new ArgumentException("Copy must belong to this book.", nameof(copy));
			_copies.Remove(copy);
		}
	}
}
