using LibrarySystem.Domain.Enums;
using System.Net;

namespace LibrarySystem.Domain
{
	/// <summary>
	/// Represents a physical copy of a book in the library system.
	/// </summary>
	public class Copy
	{
		/// <summary>
		/// Unique identifier for this copy.
		/// </summary>
		public int CopyId { get; private set; }

		/// <summary>
		/// Book associated with this copy.
		/// </summary>
		public Book Book { get; } = null!;

		/// <summary>
		/// Current state of the copy.
		/// </summary>
		public CopyState State { get; private set; }

		/// <summary>
		/// Private parameterless constructor for ORM use only.
		/// </summary>
		private Copy() { }

		/// <summary>
		/// Constructor for a Copy.
		/// </summary>
		/// <param name="book">The book associated with this copy.</param>
		/// <exception cref="ArgumentNullException">Thrown if <paramref name="book"/> is null.</exception>
		public Copy(Book book)
		{
			Book = book ?? throw new ArgumentNullException(nameof(book));
			State = CopyState.Available;
		}

		/// <summary>
		/// Sets the unique identifier of the copy after it has been generated by the database.
		/// </summary>
		/// <param name="id">The ID value returned by the database upon insertion.</param>
		/// <exception cref="ArgumentException">
		/// Thrown when <paramref name="id"/> is zero or negative.
		/// </exception>
		/// <exception cref="InvalidOperationException">
		/// Thrown when the copy ID has already been set.
		/// </exception>
		internal void SetId(int id)
		{
			if (id <= 0)
				throw new ArgumentException("ID must be positive.", nameof(id));

			if (CopyId != 0)
				throw new InvalidOperationException("ID has already been set.");

			CopyId = id;
		}

		/// <summary>
		/// Marks the copy as on loan.
		/// </summary>
		/// <exception cref="InvalidOperationException">Thrown if the copy is not available.</exception>
		public void MarkOnLoan()
		{
			if (State != CopyState.Available)
				throw new InvalidOperationException("Copy is not available for loan.");

			State = CopyState.OnLoan;
		}

		/// <summary>
		/// Marks the copy as available.
		/// </summary>
		/// <exception cref="InvalidOperationException">Thrown if the copy is not on loan.</exception>
		public void MarkAvailable()
		{
			if (State != CopyState.OnLoan)
				throw new InvalidOperationException("Only loaned copies can be returned.");

			State = CopyState.Available;
		}
	}
}
