using System.Net;

namespace LibrarySystem.Domain
{
    /// <summary>
    /// Represents a copy loan from a library user.
    /// </summary>
    public class Loan
    {
        /// <summary>
        /// Unique identifier for this loan.
        /// </summary>
        public int LoanId { get; private set; }

		/// <summary>
		/// Identifier of the loan user.
		/// </summary>
		public User User { get; private set; } = null!;

		/// <summary>
		/// Identifier of the loan copy.
		/// </summary>
		public Copy Copy { get; private set; } = null!;

		/// <summary>
		/// Borrowed date of the loan.
		/// </summary>
		public DateOnly BorrowedDate { get; private set; }

        /// <summary>
        /// Due date of the loan.
        /// </summary>
        public DateOnly DueDate { get; private set; }

        /// <summary>
        /// Return date of the loan.
        /// </summary>
		public DateOnly? ReturnedDate { get; private set; }

		/// <summary>
		/// Private parameterless constructor for ORM use only.
		/// </summary>
		private Loan() { }

		/// <summary>
		/// Constructor for a Loan.
		/// </summary>
		/// <param name="user">The user associated with this loan.</param>
		/// <param name="copy">The copy being loaned.</param>
		/// <param name="borrowedDate">Date when the loan starts.</param>
		/// <param name="dueDate">Due date for return.</param>
		/// <exception cref="ArgumentNullException">
		/// Thrown if <paramref name="user"/> or <paramref name="copy"/> is null.
		/// </exception>
		/// <exception cref="ArgumentException">
		/// Thrown if <paramref name="dueDate"/> is earlier than <paramref name="borrowedDate"/>.
		/// </exception>
		public Loan(User user, Copy copy, DateOnly borrowedDate, DateOnly dueDate)
        {
			User = user ?? throw new ArgumentNullException(nameof(user));
            Copy = copy ?? throw new ArgumentNullException(nameof(copy));

			var loanPeriod = dueDate.DayNumber - borrowedDate.DayNumber;

			if (loanPeriod > 30)
				throw new ArgumentException("Loan period cannot exceed 30 days.", nameof(dueDate));

			if (dueDate < borrowedDate)
                throw new ArgumentException("Due date cannot be earlier than borrowed date.");

			BorrowedDate = borrowedDate;
            DueDate = dueDate;
		}

		/// <summary>
		/// Sets the unique identifier of the loan after it has been generated by the database.
		/// </summary>
		/// <param name="id">The ID value returned by the database upon insertion.</param>
		/// <exception cref="ArgumentException">
		/// Thrown when <paramref name="id"/> is zero or negative.
		/// </exception>
		/// <exception cref="InvalidOperationException">
		/// Thrown when the loan ID has already been set.
		/// </exception>
		internal void SetId(int id)
		{
			if (id <= 0)
				throw new ArgumentException("ID must be positive.", nameof(id));

			if (LoanId != 0)
				throw new InvalidOperationException("ID has already been set.");

			LoanId = id;
		}

		/// <summary>
		/// Checks whether a loan is active.
		/// </summary>
		/// <returns>True if the loan is active; otherwise, false.</returns>
		public bool IsActive()
        {
            return ReturnedDate == null;
        }

		/// <summary>
		/// Checks whether a loan is overdue.
		/// </summary>
		/// <returns>True if the loan is overdue; otherwise, false.</returns>
		public bool IsOverdue(DateOnly? today)
		{
			var current = today ?? DateOnly.FromDateTime(DateTime.Now);
			return IsActive() && current > DueDate;
		}

		/// <summary>
		/// Extends a loan due date.
		/// </summary>
		/// <param name="newDueDate">New loan due date.</param>
		/// <exception cref="InvalidOperationException">Thrown if new due date is earlier than current due date.</exception>
		public void ExtendDueDate(DateOnly newDueDate)
        {
			if (ReturnedDate is not null)
				throw new InvalidOperationException("The copy has already been returned.");

			if (newDueDate < DueDate)
				throw new InvalidOperationException("New due date cannot be earlier than current due date.");   

			DueDate = newDueDate;
		}

        /// <summary>
        /// Marks a loaned copy as returned.
        /// </summary>
        /// <param name="returnDate">Loan return date.</param>
        /// <exception cref="InvalidOperationException">
        /// Thrown if copy has already been returned or return date is earlier than borrowed date.
        /// </exception>
		public void MarkAsReturned(DateOnly returnDate)
        {
            if (ReturnedDate is not null)
                throw new InvalidOperationException("The copy has already been returned.");

			if (returnDate < BorrowedDate)
				throw new InvalidOperationException("Return date cannot be earlier than borrowed date.");

            ReturnedDate = returnDate;
		}
    }
}
