using System.Net;

namespace LibrarySystem.Domain
{
	/// <summary>
	/// Represents a user in the library system.
	/// </summary>
	public class User
	{
		/// <summary>
		/// Maximum allowed length for user names.
		/// </summary>
		public const int MaxNameLength = 50;

		/// <summary>
		/// Unique identifier of the user.
		/// </summary>
		public int UserId { get; private set; }

		/// <summary>
		/// Name of the user.
		/// </summary>
		public string Name { get; private set; } = null!;

		/// <summary>
		/// Private parameterless constructor for ORM use only.
		/// </summary>
		private User() { }

		/// <summary>
		/// Constructor for a User.
		/// </summary>
		/// <param name="name">Name of the user; cannot be null or empty.</param>
		/// <exception cref="ArgumentException">Thrown if <paramref name="name"/> is null or whitespace.</exception>
		public User(string name)
		{
			if (string.IsNullOrWhiteSpace(name))
				throw new ArgumentException("Name cannot be empty.", nameof(name));

			if (name.Length > MaxNameLength)
				throw new ArgumentException($"Name cannot exceed {MaxNameLength} characters.", nameof(name));

			Name = name;
		}

		/// <summary>
		/// Sets the unique identifier of the user after it has been generated by the database.
		/// </summary>
		/// <param name="id">The ID value returned by the database upon insertion.</param>
		/// <exception cref="ArgumentException">
		/// Thrown when <paramref name="id"/> is zero or negative.
		/// </exception>
		/// <exception cref="InvalidOperationException">
		/// Thrown when the user ID has already been set.
		/// </exception>
		internal void SetId(int id)
		{
			if (id <= 0)
				throw new ArgumentException("ID must be positive.", nameof(id));

			if (UserId != 0)
				throw new InvalidOperationException("ID has already been set.");

			UserId = id;
		}
	}
}
